# Generated by Django 4.2.1 on 2023-05-31 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, verbose_name='plate number')),
                ('vin_code', models.CharField(max_length=100, verbose_name='vin code')),
                ('customer', models.CharField(max_length=100, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'ordering': ['car_model'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('engine', models.CharField(blank=True, max_length=100, null=True, verbose_name='engine')),
                ('year', models.DateField(blank=True, null=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'car model',
                'verbose_name_plural': 'car models',
                'ordering': ['make'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('order_sum', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='order sum')),
                ('status', models.PositiveBigIntegerField(choices=[(0, 'Registered'), (1, 'Waiting'), (2, 'Being fixed'), (3, 'Fixed'), (4, 'Returned'), (5, 'Canceled')], db_index=True, default=0, verbose_name='status')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autoservisas.car', verbose_name='car')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entrys', to='autoservisas.service', verbose_name='service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entrys', to='autoservisas.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order entry',
                'verbose_name_plural': 'order entries',
                'ordering': ['service'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoservisas.carmodel', verbose_name='car model'),
        ),
    ]
