# Generated by Django 4.2.1 on 2023-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_remove_orderentry_amount_orderentry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18, verbose_name='quantity'),
        ),
    ]
