# Generated by Django 4.2.1 on 2023-06-06 10:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_car_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='note',
            field=tinymce.models.HTMLField(blank=True, max_length=100, null=True, verbose_name='note'),
        ),
    ]
