# Generated by Django 4.2.1 on 2023-06-07 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0008_alter_car_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='note',
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True, verbose_name='note'),
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created')),
                ('content', models.TextField(max_length=4000, verbose_name='content')),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments', to=settings.AUTH_USER_MODEL, verbose_name='commenter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoservisas.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order comment',
                'verbose_name_plural': 'order comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
