# Generated by Django 4.2.1 on 2023-06-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0009_alter_car_note_ordercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
